# Menus
menu:
  主页: .
  笔记: archives
  杂文: categories/essay
  关于: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    highlight: monokai
    favicon: favicon.ico # path to favicon

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search

# Comment
comment:
    gitalk:
        clientID: 1fabec40f979bccf8d4b
        clientSecret: b303e92f0dfe9d538517ef7d2663dfbf62dd3b7b
        repo: dmxiaoshen.github.io
        owner: dmxiaoshen
        admin: dmxiaoshen
        distractionFreeMode: true

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 84405cc8993d00d19f760d6fa7ec02ca # enter Baidu Analytics hash key
    mathjax: false # options: true, false
