# Menus
menu:
  主页: .
  文章列表: archives
  收藏: favorites
  #分类: categories
  #标签: tags
  #关于: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar:  # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 故里
        email: '邮箱: hsg@dmxiaoshen.com'
        author_title: 爱在爱人所到之处滋长
        location: HangZhou, China
        follow: https://github.com/dmxiaoshen/
    highlight: monokai
    sidebar:  # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: favicon.ico # path to favicon
    social_links:
        #github: https://github.com/dmxiaoshen/
        #twitter: /
        #facebook: /
        #dribbble: /
        #rss: /
    social_link_tooltip: false # enable the social link tooltip, options: true, false

# Widgets
widgets:
    #- recent_posts
    #- category
    #- archive
    #- tag
    #- tagcloud
    #- links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #dmxiaoshen #your github ID
        repo: #dmxiaoshen.github.io #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #1fabec40f979bccf8d4b #your client ID
        client_secret: #b303e92f0dfe9d538517ef7d2663dfbf62dd3b7b #your client secret
    gitalk:
        clientID: 1fabec40f979bccf8d4b
        clientSecret: b303e92f0dfe9d538517ef7d2663dfbf62dd3b7b
        repo: dmxiaoshen.github.io
        owner: dmxiaoshen
        admin: dmxiaoshen
        distractionFreeMode: true
    livere: # enter livere uid here
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable
        appId:  # enter the leancloud application appId here
        appKey: # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: #Just Do It # enter the comment box placeholder


# Share
share: # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: 84405cc8993d00d19f760d6fa7ec02ca # enter Baidu Analytics hash key
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
